os: osx

matrix:
    include:
        - osx_image: xcode7.1
          env: image=xcode7.1
        - osx_image: xcode7
          env: image=xcode7

install:
    - ls -d1 /usr/local/Cellar/*/*/
    - "cat /usr/local/var/postgres/PG_VERSION || true"
    - echo $image
script: true
