language: python
python: '2.7'
env: DJANGO_VERSION=1.6.7
services:
- redis-server
- mysql
dist:
- trusty
sudo:
- required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_install:
- true
install:
- true
before_script:
- true
script:
- true
group: stable
os: linux

