language: ruby
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: precise
      sudo: required
    - os: linux
      sudo: false
    - os: osx
script:
    - df -h
install:
    - true

