language: ruby
#python: '2.7'
#group: stable
os: osx

matrix:
    include:
        - osx_image: xcode8
          env: image=xcode8
        - osx_image: "xcode7.3"
          env: image=xcode7.3
        - osx_image: "xcode7.2"
          env: image=xcode7.2
        - osx_image: "xcode7.1"
          env: image=xcode7.1
        - osx_image: "xcode7"
          env: image=xcode7
        - osx_image: "xcode6.4"
          env: image=xcode6.4
        - osx_image: "beta-xcode6.3"
          env: image=beta-xcode6.3
        - osx_image: "beta-xcode6.2"
          env: image=beta-xcode6.2
        - osx_image: "beta-xcode6.1"
          env: image=beta-xcode6.1

install:
    - ls -d1 /usr/local/Cellar/*/*/
    - "cat /usr/local/var/postgres/PG_VERSION || true"
    - echo $image
script: true
